deepspeed --module openrlhf.cli.train_sft \
          --save_path ./output_hotpotqa_direct_grounding_qwen \
          --save_steps 25 \
          --save_hf_ckpt \
          --ckpt_path ./checkpoint_hotpotqa_direct_grounding_qwen \
          --logging_steps 5 \
          --eval_steps 50 \
          --max_ckpt_num 1 \
          --load_checkpoint \
          --max_len 133120 \
          --dataset ./hotpotqa_data_direct_grounding_qwen/train.jsonl \
          --eval_dataset ./hotpotqa_data_direct_grounding_qwen/dev.jsonl \
          --input_key messages \
          --train_batch_size 64 \
          --micro_train_batch_size 1 \
          --max_samples 100000 \
          --pretrain Qwen/Qwen3-4B-Instruct-2507 \
          --seed 42 \
          --zero_stage 2 \
          --max_epochs 5 \
          --packing_samples \
          --bf16 \
          --attn_implementation flash_attention_2 \
          --learning_rate 5e-6 \
          --lr_warmup_ratio 0.1 \
          --lr_scheduler cosine_with_min_lr \
          --gradient_checkpointing \
          --use_liger_kernel \
          --ds_tensor_parallel_size 1 \
          --adam_offload \
          --ring_attn_size 4 \
          --apply_chat_template \
          --wandb_project longtune \
          --wandb_run_name direct_grounding_hotpotqa_qwen \
          --use_wandb 89fc8b0a9054e79e977cbfd14e2804d4022701d0